word = input("Enter any word: ")

print("Word in uppercase: ", word.upper())
print("Word in lowercase: ", word.lower())
print("Length of the word: ", len(word))
print("First character: ", word[0])
print("Last character: ", word[-1])
print("Reversed word: ", word[::-1])
print("Is 'a' in the word? ", 'a' in word)
# print("Replace 'a' with '*': ", word.replace('a', '*'))
# print("Replace 'e' with '*': ", word.replace('e', '*'))
# print("Replace 'i' with '*': ", word.replace('i', '*'))
# print("Replace 'o' with '*': ", word.replace('o', '*'))
# print("Replace 'u' with '*': ", word.replace('u', '*'))
if('a' or 'e' or 'i' or 'o' or 'u' in word):
    print("Replace vowels with '*': ", word.replace('a', '*').replace('e', '*').replace('i', '*').replace('o', '*').replace('u', '*'))