word = input("Enter any word: ")

print("Word in uppercase: ", word.upper())
print("Word in lowercase: ", word.lower())
print("Length of the word: ", len(word))
print("First character: ", word[0])
print("Last character: ", word[-1])
print("Reversed word: ", word[::-1])
print("Is 'a' in the word? ", 'a' in word)
print("Replace vowels with '*': ", word.replace('a', '*').replace('e', '*').replace('i', '*').replace('o', '*').replace('u', '*'))